services:
  service-redis:
    image: bitnami/redis
    ports:
      - '6379:6379'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes

  app:
    build: .
    environment:
      - POSTGRES_URL=${POSTGRES_URL}
    command: ["npm", "run", "migrate"]


volumes:
  - pg_data:/bitnami/postgresql