services:
  service-redis:
    image: bitnami/redis
    ports:
      - '6379:6379'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes

  app:
    build: .
    environment:
      - PORT=${PORT}
      - POSTGRES_URL=${DATABASE_URL} 
      - WEB_URL=${WEB_URL}
      - REDIS_URL=redis://service-redis:6379
    depends_on:
      - service-redis
