services:
  service-redis:
    image: bitnami/redis
    ports:
      - '6379:6379'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes

  app:
    build: .
    environment:
      - POSTGRES_URL=${DATABASE_URL}
      - REDIS_HOST=service-redis
      - REDIS_PORT=6379
    depends_on:
      - service-redis
    command: ["npm", "run", "migrate"]
